
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef ENCODER_SLAVE_H
#define ENCODER_SLAVE_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 Encoder_Slave_valueRangeTest (UNS8 typeValue, void * value);
const indextable * Encoder_Slave_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data Encoder_Slave_Data;
extern UNS64 Encoder_Raw_Data;		/* Mapped at index 0x2000, subindex 0x00*/
extern UNS32 Multiturn_Data;		/* Mapped at index 0x2001, subindex 0x00*/
extern UNS32 SingleTurn_Data;		/* Mapped at index 0x2002, subindex 0x00*/
extern UNS8 Warning_Data;		/* Mapped at index 0x2003, subindex 0x00*/
extern UNS8 Error_Data;		/* Mapped at index 0x2004, subindex 0x00*/
extern UNS16 CRC_Data;		/* Mapped at index 0x2005, subindex 0x00*/

#endif // ENCODER_SLAVE_H
